INSERT INTO ADDRESS (id, country, city) VALUES (111, 'TURKIYE', 'Ankara');
INSERT INTO ADDRESS (id, country, city) VALUES (121, 'Germany', 'Berlin');
INSERT INTO ADDRESS (id, country, city) VALUES (141, 'Italy', 'Rome');
INSERT INTO ADDRESS (id, country, city) VALUES (131, 'France', 'Paris');
INSERT INTO ADDRESS (id, country, city) VALUES (151, 'England', 'London');
INSERT INTO ADDRESS (id, country, city) VALUES (161, 'Portugal', 'Lisbon');
INSERT INTO ADDRESS (id, country, city) VALUES (171, 'Spain', 'Madrid');
INSERT INTO ADDRESS (id, country, city) VALUES (181, 'Austria', 'Vienna');
INSERT INTO ADDRESS (id, country, city) VALUES (191, 'Bulgaria', 'Sofia');
